items = ['ZENFASULYE', 'ELMAS', 'ISILANMAYUZUGU', 'TASPARCASI', 'KURBAGADILI', 'RUZGARINAYAKKABILARI',
         'ALTININCI', 'DOMUZBURNU', 'MAVIIKSIR', 'YASAMKUTSAMASI', 'BAKIR', 'TURUNCUSEBNEM', 'EFSUNNESNESI',
         'AYISAFRASI', 'EJDERHAPULU', 'EPKUPONU', 'KIRMIZIKSIR', 'DEMIRCININELKITABI', 'CESARETPELERINI',
         'KANTASI', 'SOZYUZUGU', 'YESILIKSIR', 'ATSEKERI', 'DUYGUMASKESI', 'BUYULUMETAL', 'TECRUBEYUZUGU',
         'DELICIISABET', 'EJDERHAPENCESI', 'PEMBEINCI', 'SIYAHBOYA', 'UCUNCUEL', 'MORIKSIR',
         'SARISEBNEM', 'DUT', 'KRITIKISABET', 'ZUMRUT', 'ALTINFUTBOLTOPU', 'KUWARSKUMU', 'YESILEFSUN',
         'TICARETCAMI', 'BEYAZBOYA', 'HIZTASI', 'AYTASI', 'SAVASKAGIDI', 'KILCIK']
